// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using PictureStampRally.Models;

namespace PictureStampRally.Models
{
    public static partial class EventInfoCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<EventInfo> DeserializeJson(JToken inputObject)
        {
            IList<EventInfo> deserializedObject = new List<EventInfo>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                EventInfo eventInfo = new EventInfo();
                eventInfo.DeserializeJson(iListValue);
                deserializedObject.Add(eventInfo);
            }
            return deserializedObject;
        }
    }
}
