// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using PictureStampRally.Models;

namespace PictureStampRally.Models
{
    public static partial class ThemeInfoCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<ThemeInfo> DeserializeJson(JToken inputObject)
        {
            IList<ThemeInfo> deserializedObject = new List<ThemeInfo>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                ThemeInfo themeInfo = new ThemeInfo();
                themeInfo.DeserializeJson(iListValue);
                deserializedObject.Add(themeInfo);
            }
            return deserializedObject;
        }
    }
}
