// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using PictureStampRally.Models;

namespace PictureStampRally.Models
{
    public static partial class ThemeItemCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<ThemeItem> DeserializeJson(JToken inputObject)
        {
            IList<ThemeItem> deserializedObject = new List<ThemeItem>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                ThemeItem themeItem = new ThemeItem();
                themeItem.DeserializeJson(iListValue);
                deserializedObject.Add(themeItem);
            }
            return deserializedObject;
        }
    }
}
