// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using PictureStampRally;
using PictureStampRally.Models;

namespace PictureStampRally
{
    public static partial class ScoreExtensions
    {
        /// <param name='operations'>
        /// Reference to the PictureStampRally.IScore.
        /// </param>
        /// <param name='file'>
        /// Required. アップロードするファイル
        /// </param>
        /// <param name='themeImageId'>
        /// Required. id
        /// </param>
        public static ScoreCheckResult Check(this IScore operations, Stream file, int themeImageId)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IScore)s).CheckAsync(file, themeImageId);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the PictureStampRally.IScore.
        /// </param>
        /// <param name='file'>
        /// Required. アップロードするファイル
        /// </param>
        /// <param name='themeImageId'>
        /// Required. id
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<ScoreCheckResult> CheckAsync(this IScore operations, Stream file, int themeImageId, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<PictureStampRally.Models.ScoreCheckResult> result = await operations.CheckWithOperationResponseAsync(file, themeImageId, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the PictureStampRally.IScore.
        /// </param>
        /// <param name='file'>
        /// Required. アップロードするファイル
        /// </param>
        /// <param name='themeImageId'>
        /// Required. id
        /// </param>
        public static ScoreCheckResult Regist(this IScore operations, Stream file, int themeImageId)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IScore)s).RegistAsync(file, themeImageId);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the PictureStampRally.IScore.
        /// </param>
        /// <param name='file'>
        /// Required. アップロードするファイル
        /// </param>
        /// <param name='themeImageId'>
        /// Required. id
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<ScoreCheckResult> RegistAsync(this IScore operations, Stream file, int themeImageId, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<PictureStampRally.Models.ScoreCheckResult> result = await operations.RegistWithOperationResponseAsync(file, themeImageId, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
