// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using PictureStampRally;
using PictureStampRally.Models;

namespace PictureStampRally
{
    public static partial class ThemeImagesExtensions
    {
        /// <param name='operations'>
        /// Reference to the PictureStampRally.IThemeImages.
        /// </param>
        /// <param name='eventId'>
        /// Required.
        /// </param>
        public static IList<ThemeItem> Get(this IThemeImages operations, int eventId)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IThemeImages)s).GetAsync(eventId);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the PictureStampRally.IThemeImages.
        /// </param>
        /// <param name='eventId'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<ThemeItem>> GetAsync(this IThemeImages operations, int eventId, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<PictureStampRally.Models.ThemeItem>> result = await operations.GetWithOperationResponseAsync(eventId, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
