//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictureStampRally.WebApi.Models.DB
{
    using System;
    using System.Data.SqlClient;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int ThemeImageId { get; set; }
        public int ScoreValue { get; set; }
    
        public virtual ThemeImage ThemeImage { get; set; }

        public static SqlDataReader getScore()
        {
            SqlConnection conn = new SqlConnection();
            SqlCommand command = new SqlCommand();

            conn.ConnectionString = @"Data Source = connect2016-fcs-team-z.database.windows.net;"
                                        + "Initial Catalog = fcs;"
                                        + "Integrated Security=False;"
                                        + "User ID = fcs;"
                                        + "Password = Pass1234";
            conn.Open();

            command.Connection = conn;
            command.CommandText = "SELECT * FROM dbo.Score";

            SqlDataReader reader = command.ExecuteReader();
            return reader;
        }
    }
}
