//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictureStampRally.WebApi.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThemeImage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThemeImage()
        {
            this.HintProvider = new HashSet<HintProvider>();
        }
    
        public int Id { get; set; }
        public int EventId { get; set; }
        public string HintAddr { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Score Score { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HintProvider> HintProvider { get; set; }
    }
}
