//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictureStampRally.WebApi.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThemeImage
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public byte[] Image { get; set; }
        public string Prefecture { get; set; }
        public string City { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual HintProvider HintProvider { get; set; }
        public virtual Score Score { get; set; }
    }
}
