// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using PictureStampRally.WebApiClient;
using PictureStampRally.WebApiClient.Models;

namespace PictureStampRally.WebApiClient
{
    public static partial class EventsExtensions
    {
        /// <param name='operations'>
        /// Reference to the PictureStampRally.WebApiClient.IEvents.
        /// </param>
        public static IList<EventInfo> Get(this IEvents operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IEvents)s).GetAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the PictureStampRally.WebApiClient.IEvents.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<EventInfo>> GetAsync(this IEvents operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<PictureStampRally.WebApiClient.Models.EventInfo>> result = await operations.GetWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
