// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using PictureStampRally.WebApiClient.Models;

namespace PictureStampRally.WebApiClient
{
    public partial interface IScore
    {
        /// <param name='file'>
        /// Required. アップロードするファイル
        /// </param>
        /// <param name='themeImageId'>
        /// Required. id
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<ScoreCheckResult>> CheckWithOperationResponseAsync(Stream file, int themeImageId, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='file'>
        /// Required. アップロードするファイル
        /// </param>
        /// <param name='themeImageId'>
        /// Required. id
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<ScoreCheckResult>> RegistWithOperationResponseAsync(Stream file, int themeImageId, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
