// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;

namespace PictureStampRally.WebApiClient
{
    public partial interface IThemeImage
    {
        /// <param name='file'>
        /// Required. アップロードするファイル
        /// </param>
        /// <param name='eventId'>
        /// Required. イベントID
        /// </param>
        /// <param name='hintAddr'>
        /// Required. だいたいの場所
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> PostWithOperationResponseAsync(Stream file, int eventId, string hintAddr, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='file'>
        /// Required. アップロードするファイル
        /// </param>
        /// <param name='themeImageId'>
        /// Required. イメージID
        /// </param>
        /// <param name='hintAddr'>
        /// Required. だいたいの場所
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> PutWithOperationResponseAsync(Stream file, int themeImageId, string hintAddr, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
