// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using PictureStampRally.WebApiClient;
using PictureStampRally.WebApiClient.Models;

namespace PictureStampRally.WebApiClient
{
    public static partial class ThemeInfoOperationsExtensions
    {
        /// <param name='operations'>
        /// Reference to the
        /// PictureStampRally.WebApiClient.IThemeInfoOperations.
        /// </param>
        /// <param name='eventId'>
        /// Required.
        /// </param>
        public static IList<ThemeInfo> Get(this IThemeInfoOperations operations, int eventId)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IThemeInfoOperations)s).GetAsync(eventId);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the
        /// PictureStampRally.WebApiClient.IThemeInfoOperations.
        /// </param>
        /// <param name='eventId'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<ThemeInfo>> GetAsync(this IThemeInfoOperations operations, int eventId, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<PictureStampRally.WebApiClient.Models.ThemeInfo>> result = await operations.GetWithOperationResponseAsync(eventId, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
